// web/src/components/WhatsappTemplateRecipientForm.tsx
import { useForm } from '@tanstack/react-form'
import { Button } from '#/components/ui/button'
import { Card, CardContent, CardFooter, CardHeader } from '#/components/ui/card'
import { Input } from '#/components/ui/input'
import { Label } from '#/components/ui/label'
import { useToast } from '#/hooks/useToast'
import { useLoading } from '#/hooks/useLoading'
import { getTemplateService } from '#/modules/template/service'
import { db } from '#/lib/firebase'
import type { Recipient } from '#/modules/template/interfaces'

interface WhatsappTemplateRecipientFormProps {
  templateId: string
  id?: string
  value?: Recipient
  title?: string
  onFinish?: () => void
}

export function WhatsappTemplateRecipientForm({
  templateId,
  id,
  value = { name: '', contactNumber: '', labels: {} },
  title,
  onFinish,
}: WhatsappTemplateRecipientFormProps) {
  const { toast } = useToast()
  const [isLoading, loading] = useLoading()
  const service = getTemplateService(db)

  const form = useForm({
    defaultValues: value,
    onSubmit: async ({ value: formValue }) => {
      await loading(
        (id
          ? service.updateRecipient(templateId, id, formValue)
          : service.addRecipient(templateId, formValue)
        ).then(() => {
          toast({
            title: id ? 'Recipient updated' : 'Recipient added',
          })
          onFinish?.()
        }),
      )
    },
  })

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault()
        e.stopPropagation()
        form.handleSubmit()
      }}
    >
      <Card className="max-w-lg">
        <CardHeader>{title || `${id ? 'Edit' : 'Add'} Recipient`}</CardHeader>
        <CardContent className="space-y-4">
          <form.Field
            name="name"
            children={(field) => (
              <div className="space-y-2">
                <Label htmlFor={field.name}>
                  Person Name or Group Name
                  <span className="text-red-500">*</span>
                </Label>
                <Input
                  id={field.name}
                  value={field.state.value}
                  onBlur={field.handleBlur}
                  onChange={(e) => field.handleChange(e.target.value)}
                />
              </div>
            )}
          />

          <form.Field
            name="contactNumber"
            children={(field) => (
              <div className="space-y-2">
                <Label htmlFor={field.name}>Contact Number</Label>
                <Input
                  id={field.name}
                  type="tel"
                  value={field.state.value || ''}
                  onBlur={field.handleBlur}
                  onChange={(e) => field.handleChange(e.target.value)}
                  placeholder="Required for person"
                />
              </div>
            )}
          />

          <form.Field
            name="labels"
            children={(field) => {
              const labels = field.state.value || {}
              const labelEntries = Object.entries(labels)

              return (
                <div className="space-y-3">
                  {labelEntries.concat([['', '']]).map(([key, val], i) => (
                    <div key={i} className="space-y-2">
                      <Label>Label {i + 1}</Label>
                      <div className="flex gap-2">
                        <Input
                          value={key}
                          onChange={(e) => {
                            const newKey = e.target.value
                            const newLabels = { ...labels }
                            if (key) delete newLabels[key]
                            if (newKey) newLabels[newKey] = val
                            field.handleChange(newLabels)
                          }}
                          placeholder={`Key of Label ${i + 1}`}
                          className="flex-1"
                        />
                        <Input
                          value={val}
                          onChange={(e) => {
                            if (key) {
                              field.handleChange({
                                ...labels,
                                [key]: e.target.value,
                              })
                            }
                          }}
                          placeholder={`Value of Label ${i + 1}`}
                          className="flex-1"
                          disabled={!key}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              )
            }}
          />
        </CardContent>
        <CardFooter>
          <Button type="submit" disabled={isLoading}>
            {isLoading ? 'Saving...' : 'Save'}
          </Button>
        </CardFooter>
      </Card>
    </form>
  )
}

// web/components/WhatsappTemplateRecipientForm.vue
<script lang="ts" setup>
import { camelCase } from 'change-case';
import type { FormSubmitEvent } from '#ui/types';
import type { InRecipient } from '~/modules/template/interfaces';
import { RecipientSchema } from '~/modules/template/schemas';
import useTemplateStore from '~/stores/template';

interface Props {
  /** If undefined then it's a new recipient */
  id?: string;
  value?: InRecipient;
  title?: string;
}

interface Emits {
  (event: 'finish'): void;
}

const props = withDefaults(defineProps<Props>(), {
  value: () => ({
    name: '',
  }),
  id: undefined,
  title: undefined,
});
const emit = defineEmits<Emits>();

const store = useTemplateStore();

const fields = ref(props.value);

const toast = useToast();
const [isLoading, loading] = useLoading();

const onSubmit = async (ev: FormSubmitEvent<InRecipient>) => {
  try {
    if (props.id) await loading(store.updateRecipient(props.id, ev.data));
    else await loading(store.addRecipient(ev.data));

    toast.add({ title: props.id ? 'Recipient updated' : 'Recipient added' });
  } finally {
    emit('finish');
  }
};
</script>

<template>
  <u-form
    :state="fields"
    :schema="RecipientSchema"
    @submit="onSubmit"
  >
    <u-card class="max-w-lg">
      <template #header>
        {{ props.title || `${id ? 'Edit' : 'Add'} Recipient` }}
      </template>

      <div class="space-y-2">
        <u-form-group
          label="Person Name or Group Name"
          name="name"
          required
        >
          <u-input v-model="fields.name" />
        </u-form-group>

        <u-form-group
          label="Contact Number"
          name="contactNumber"
        >
          <u-input
            v-model="fields.contactNumber"
            type="tel"
            placeholder="Required for person"
          />
        </u-form-group>

        <u-form-group
          v-for="(v, k, i) in {...fields.labels, '': ''}"
          :key="i"
          :label="`Label ${i + 1}`"
          :name="camelCase(`label ${i + 1}`)"
          required
        >
          <div class="flex gap-2">
            <u-input
              :model-value="k"
              :model-modifiers="{lazy: true}"
              :placeholder="`Key of Label ${i + 1}`"
              class="grow"
              @update:model-value="fields.labels = { ...fields.labels, [$event]: v }"
            />
            <u-input
              :model-value="v"
              :placeholder="`Value of Label ${i + 1}`"
              class="grow"
              :disabled="!k"
              @update:model-value="fields.labels = { ...fields.labels, [k]: $event }"
            />
          </div>
        </u-form-group>
      </div>

      <template #footer>
        <u-button
          type="submit"
          label="Save"
          :loading="isLoading"
        />
      </template>
    </u-card>
  </u-form>
</template>
