// web/src/components/CsvImporter.tsx
import { Badge } from '#/components/ui/badge';
import { Button } from '#/components/ui/button';
import { Card, CardContent, CardFooter, CardHeader } from '#/components/ui/card';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from '#/components/ui/table';
import { useLoading } from '#/hooks/useLoading';
import { Trash2 } from 'lucide-react';
import { nanoid } from 'nanoid';
import Papa from 'papaparse';
import { useEffect, useState } from 'react';

interface CsvImporterProps {
  onImport: (data: Record<string, unknown>[]) => void;
}

const parseFile = async (file: File): Promise<Record<string, unknown>[]> => {
  return new Promise((resolve, reject) => {
    Papa.parse(file, {
      header: true,
      skipEmptyLines: true,
      complete: (results) => {
        resolve(results.data as Record<string, unknown>[]);
      },
      error: (error) => {
        reject(error);
      },
    });
  });
};

const excludes = <T,>(arr: T[], ...items: T[]): T[] => {
  return arr.filter((item) => !items.includes(item));
};

export function CsvImporter({ onImport }: CsvImporterProps) {
  const [isLoading, loading] = useLoading();
  const [source, setSource] = useState<File>();
  const [data, setData] = useState<Array<Record<string, unknown> & { $id: string }>>([]);
  const [dataCols, setDataCols] = useState<string[]>([]);
  const [colNameFields, setColNameFields] = useState({
    name: 'name',
    contactNumber: 'contactNumber',
  });
  const [includeAsLabels, setIncludeAsLabels] = useState<string[]>([]);

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setSource(file);
  };

  const handleImportClick = () => {
    const imported = data.map(({ $id, [colNameFields.name]: name, [colNameFields.contactNumber]: contactNumber, ...cols }) => ({
      name,
      contactNumber,
      labels: Object.fromEntries(
        Object.entries(cols).filter(([k]) => includeAsLabels.includes(k))
      ),
    }));
    onImport(imported);
  };

  const handleRowDelete = (id: string) => {
    setData((prev) => prev.filter((row) => row.$id !== id));
  };

  useEffect(() => {
    if (!source) return;

    loading(
      parseFile(source).then((parsed) => {
        const withIds = parsed.map((el) => ({ ...el, $id: nanoid() }));
        setData(withIds);
        const cols = [...new Set(parsed.flatMap((row) => Object.keys(row)))];
        setDataCols(cols);
      })
    );
  }, [source]);

  useEffect(() => {
    setIncludeAsLabels((prev) =>
      excludes(prev, colNameFields.name, colNameFields.contactNumber)
    );
  }, [colNameFields.name, colNameFields.contactNumber]);

  const columns = [
    { key: colNameFields.name, label: 'Name' },
    { key: colNameFields.contactNumber, label: 'Contact Number' },
    { key: 'labels', label: 'Labels' },
    { key: 'actions', label: '' },
  ];

  return (
    <Card>
      <CardHeader>Import CSV</CardHeader>
      <CardContent className="space-y-6">
        <ol className="space-y-4 list-decimal list-inside">
          <li>
            <div className="ml-2 space-y-2">
              <span className="font-medium">Choose a file</span>
              <div className="flex gap-2 items-center">
                <Button variant="outline" className="relative">
                  Choose
                  <label className="absolute inset-0 cursor-pointer">
                    <input
                      type="file"
                      accept=".csv"
                      className="hidden"
                      onChange={handleFileChange}
                    />
                  </label>
                </Button>
                {source && <span className="text-sm">{source.name}</span>}
              </div>
            </div>
          </li>

          <li>
            <div className="ml-2 space-y-2">
              <span className="font-medium">Define columns</span>
              <table className="w-full">
                <tbody>
                  <tr>
                    <th className="w-48 text-left py-2">Name</th>
                    <td>
                      <select
                        value={colNameFields.name}
                        onChange={(e) =>
                          setColNameFields((prev) => ({
                            ...prev,
                            name: e.target.value,
                          }))
                        }
                        disabled={!dataCols.length}
                        className="w-full px-3 py-2 border rounded-md"
                      >
                        {[...new Set(['name', ...dataCols])].map((col) => (
                          <option key={col} value={col}>
                            {col}
                          </option>
                        ))}
                      </select>
                    </td>
                  </tr>
                  <tr>
                    <th className="w-48 text-left py-2">Contact Number</th>
                    <td>
                      <select
                        value={colNameFields.contactNumber}
                        onChange={(e) =>
                          setColNameFields((prev) => ({
                            ...prev,
                            contactNumber: e.target.value,
                          }))
                        }
                        disabled={!dataCols.length}
                        className="w-full px-3 py-2 border rounded-md"
                      >
                        {[...new Set(['contactNumber', ...dataCols])].map((col) => (
                          <option key={col} value={col}>
                            {col}
                          </option>
                        ))}
                      </select>
                    </td>
                  </tr>
                  <tr>
                    <th className="w-48 text-left py-2 align-top">Add Labels from</th>
                    <td>
                      <div className="flex gap-2 flex-wrap">
                        {excludes(
                          dataCols,
                          colNameFields.name,
                          colNameFields.contactNumber
                        ).map((prop) => (
                          <label key={prop} className="flex items-center gap-1">
                            <input
                              type="checkbox"
                              checked={includeAsLabels.includes(prop)}
                              onChange={(e) => {
                                if (e.target.checked) {
                                  setIncludeAsLabels((prev) => [...prev, prop]);
                                } else {
                                  setIncludeAsLabels((prev) =>
                                    prev.filter((p) => p !== prop)
                                  );
                                }
                              }}
                            />
                            <span className="text-sm">{prop}</span>
                          </label>
                        ))}
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </li>

          <li>
            <div className="ml-2 space-y-2">
              <span className="font-medium">Preview your data</span>
              <div className="max-h-[40vh] overflow-auto border rounded-md">
                <Table>
                  <TableHeader>
                    <TableRow>
                      {columns.map((col) => (
                        <TableHead key={col.key}>{col.label}</TableHead>
                      ))}
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {isLoading ? (
                      <TableRow>
                        <TableCell colSpan={columns.length} className="text-center">
                          Loading...
                        </TableCell>
                      </TableRow>
                    ) : data.length === 0 ? (
                      <TableRow>
                        <TableCell colSpan={columns.length} className="text-center">
                          No data
                        </TableCell>
                      </TableRow>
                    ) : (
                      data.map((row) => (
                        <TableRow key={row.$id}>
                          <TableCell>{String(row[colNameFields.name] || '')}</TableCell>
                          <TableCell>{String(row[colNameFields.contactNumber] || '')}</TableCell>
                          <TableCell>
                            <div className="flex gap-1 flex-wrap max-w-md">
                              {Object.entries(row)
                                .filter(([k]) => includeAsLabels.includes(k))
                                .map(([key, val]) => (
                                  <Badge key={key} variant="secondary">
                                    {key}: {String(val)}
                                  </Badge>
                                ))}
                            </div>
                          </TableCell>
                          <TableCell>
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={() => handleRowDelete(row.$id)}
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          </TableCell>
                        </TableRow>
                      ))
                    )}
                  </TableBody>
                </Table>
              </div>
              <div className="flex justify-end">
                <small className="text-sm text-gray-500">{data.length} rows</small>
              </div>
            </div>
          </li>
        </ol>
      </CardContent>
      <CardFooter className="justify-end">
        <Button
          onClick={handleImportClick}
          disabled={!data.length}
        >
          Import
        </Button>
      </CardFooter>
    </Card>
  );
}

// components/CsvImporter.vue
<!-- TODO: Work for other utilities, not for recipients only.
  It receives input wanted columns, and wether to add rest columns as labels or related. -->
<script lang="ts" setup generic="T">
import { nanoid } from 'nanoid';
import { parse as parseCsv } from 'csv-parse/browser/esm/sync';
import { excludes } from '~/utils/array';

interface Emits {
  (ev: 'import', data: Record<string, unknown>[]): void;
}

const parseFile = async (file: File): Promise<Record<string, unknown>[]> => {
  const content = await file.text();
  const parsed = parseCsv(content, { columns: true, trim: true, delimiter: [',', ';'] });
  return parsed;
};

const emit = defineEmits<Emits>();

const [isLoading, loading] = useLoading();

const source = ref<File>();
const data = ref<Record<string, unknown>[]>([]);
const dataCols = ref<string[]>([]);

const colNameFields = reactive({
  name: 'name',
  contactNumber: 'contactNumber',
});
const includeAsLabels = ref<string[]>([]);

const columns = computed(() => [
  { key: colNameFields.name, label: 'Name' },
  { key: colNameFields.contactNumber, label: 'Contact Number' },
  { key: 'labels', label: 'Labels' },
  { key: 'actions', label: '' },
]);

const onFileChange = async (ev: Event) => {
  const input = ev.target as HTMLInputElement;
  const file = input.files?.[0];
  if (!file) return;

  source.value = file;
};

const onImportClick = () => {
  const imported = data.value.map(({
    [colNameFields.name]: name,
    [colNameFields.contactNumber]: contactNumber,
    ...cols
  }) => ({
    name,
    contactNumber,
    labels: Object.fromEntries(
      Object.entries(cols).filter(([k]) => includeAsLabels.value.includes(k)),
    ),
  }));
  emit('import', imported);
};

const onRowDeleteClick = (id: string) => {
  const i = data.value.findIndex((row) => row.$id === id);
  data.value.splice(i, 1);
};

whenever(source, async (v) => {
  const parsed = await loading(parseFile(v));
  data.value = parsed.map((el) => ({ ...el, $id: nanoid() }));
  dataCols.value = [...new Set(parsed.flatMap((row) => Object.keys(row)))];
});

watch(() => [colNameFields.name, colNameFields.contactNumber], (v) => {
  includeAsLabels.value = excludes(includeAsLabels.value, ...v);
});
</script>

<template>
  <u-card>
    <template #header>
      Import CSV
    </template>

    <div class="flex flex-col gap-4">
      <div class="prose prose-sm dark:prose-invert">
        <ol class="instructions">
          <li>
            <div class="flex flex-col gap-2">
              <span>Choose a file</span>
              <div class="flex gap-1.5 items-center">
                <u-button
                  icon="i-heroicons-document-arrow-up"
                  class="relative"
                >
                  Choose
                  <label class="absolute inset-0 cursor-pointer">
                    <input
                      type="file"
                      accept=".csv"
                      class="hidden"
                      @change="onFileChange"
                    >
                  </label>
                </u-button>

                <span v-if="source">{{ source.name }}</span>
              </div>
            </div>
          </li>

          <li>
            <div class="flex flex-col gap-2">
              <span>Define columns</span>
              <table class="not-prose">
                <tr>
                  <th class="w-[18ch] leading-none py-[.25em]">
                    Name
                  </th>
                  <td>
                    <u-select
                      v-model="colNameFields.name"
                      :disabled="!dataCols.length"
                      :options="[...new Set(['name', ...dataCols])]"
                    />
                  </td>
                </tr>
                <tr>
                  <th class="w-[18ch] leading-none py-[.25em]">
                    Contact Number
                  </th>
                  <td>
                    <u-select
                      v-model="colNameFields.contactNumber"
                      :disabled="!dataCols.length"
                      :options="[...new Set(['contactNumber', ...dataCols])]"
                    />
                  </td>
                </tr>
                <tr>
                  <th class="w-[18ch] leading-none py-[.25em]">
                    Add Labels from
                  </th>
                  <td>
                    <div class="flex gap-1">
                      <u-checkbox
                        v-for="(prop) in excludes(dataCols, colNameFields.name, colNameFields.contactNumber)"
                        :key="prop"
                        :label="prop"
                        :model-value="includeAsLabels.includes(prop)"
                        @update:model-value="$event
                          ? includeAsLabels.push(prop)
                          : includeAsLabels.splice(includeAsLabels.indexOf(prop), 1)"
                      />
                    </div>
                  </td>
                </tr>
              </table>
            </div>
          </li>

          <li>
            <div class="flex flex-col gap-2">
              <span>Preview your data</span>
              <u-table
                :columns="columns"
                :rows="data"
                :loading="isLoading"
                class="not-prose overflow-auto max-h-[40vh]"
              >
                <template #labels-data="{row}">
                  <div class="flex gap-1 flex-wrap max-w-[36ch]">
                    <u-badge
                      v-for="(label, key) in Object.fromEntries(
                        Object.entries(row).filter(([k]) => includeAsLabels.includes(k))
                      )"
                      :key="key"
                      :label="`${key}: ${label}`"
                      variant="soft"
                      size="xs"
                    />
                  </div>
                </template>

                <template #actions-data="{row}">
                  <u-button
                    icon="i-heroicons-trash"
                    variant="ghost"
                    square
                    color="red"
                    @click="onRowDeleteClick(row.$id)"
                  />
                </template>
              </u-table>
              <div class="flex">
                <div class="grow" />
                <small>{{ data.length }} rows</small>
              </div>
            </div>
          </li>
        </ol>
      </div>
    </div>

    <template #footer>
      <div class="flex">
        <div class="grow" />

        <u-button
          label="Import"
          color="primary"
          :disabled="!data.length"
          @click="onImportClick"
        />
      </div>
    </template>
  </u-card>
</template>
